### ISSUE TITLE
Error caching image: [Error: database or disk is full (code 13 SQLITE_FULL)]

### ISSUE THREAD

**Issue by Shivayogihc** [syednomishah/Food-Recipe-App-React-Native#1]
<img width="1728" alt="Screenshot 2023-08-31 at 12 01 23 AM" src="https://github.com/syednomishah/Food-Recipe-App-React-Native/assets/88485343/d8ba3159-463c-4444-bdba-a4cb12d51fbd">

https://github.com/syednomishah/Food-Recipe-App-React-Native/assets/88485343/37454e14-204d-4c60-8394-371689ecd01a

**Comment by yu1iaw** [comment]
Unfortunately I have the same issue. Did you use MySQL for any expo apps before?

**Comment by sahilwaikar** [comment]
I am facing same issue. I approached some experts for this. I was advised to use expo-image , as it is already built for image-caching. Or just use simple json array .

**Comment by sahilwaikar** [comment]
If You have found any solution , reply below

**Comment by syednomishah** [comment]
I've fixed this issue.
used expo-image.
